baseURL = "https://hasiru-ratha.github.io/"
languageCode = "en-us"
title = "Hasiru Ratha"
debug = true
theme = "hugo-creative-portfolio-theme"

[params]
    style = "default"
    copyright = "&copy;2019 Hasiru-Ratha"
    sidebarAbout = [
    "We are volunteer based organization planting, sustaining and maintaining trees around South Bangalore",
    "Currently active around Jayanagar, Basavanagudi, Gandhi Bazaar"
    ]

[[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

[[params.navlinks]]
  name = "About us"
  url = "about/"

[[params.navlinks]]
  name = "Volunteer with us"
  url = "volunteer/"
