baseURL = "https://hasiru-ratha.github.io/"
languageCode = "en-us"
title = "Hasiru Ratha"
debug = true
theme = "hugo-creative-portfolio-theme"

[params]
    style = "default"
    copyright = "&copy;2019 Hasiru-Ratha"
    description = "Hasiru Ratha is a volunteer based organization involved in planting and sustaining saplings around South Bangalore. Our intention is to not only plant saplings but also provide for them till they grow into trees"
    sidebarAbout = [
    "We are volunteer based organization involved in planting and sustaining saplings around South Bangalore. Our intention is to not only plant saplings but also provide for them till they grow into trees"
    ]

[[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

[[params.navlinks]]
  name = "About us"
  url = "about/"

[[params.navlinks]]
  name = "Volunteer with us"
  url = "volunteer/"

[[params.navlinks]]
  name = "Media"
  url = "media/"
